### ISSUE TITLE
assets 404

### ISSUE THREAD

**Issue by AlexisWalravens** [inetis-ch/oc-InputCounter-plugin#4]
Hello de Belgique,

Juste pour vous prévenir que j'ai du changer les lignes 29 & 30 de plugin.php

```
$controller->addCss("/plugins/inetis/inputcounter/assets/css/style.css");
$controller->addJs("/plugins/inetis/inputcounter/assets/js/main.js");
```
En

```
$controller->addCss("/plugins/inetis/inputCounter/assets/css/style.css");
$controller->addJs("/plugins/inetis/inputCounter/assets/js/main.js");
```

Car une fois en ligne ils ne chargeaient pas et renvoyaient une erreur 404 à cause de la casse du dossier `inputCounter`.

Bonne journée.

**Comment by Fl0Cri** [comment]
Hello,

Normalement il faut mettre le nom du dossier en minuscules.
Sauf erreur c'est comme ça que font les plugins du market.

Par exemple chez RainLab: https://github.com/rainlab/blogvideo-plugin/blob/master/Plugin.php#L35

Merci d'utiliser ce plugin, n'hésitez pas à nous faire vos retours!

Bonne journée

**Comment by AlexisWalravens** [comment]
Bonjour,
Oui effectivement au temps pour moi.
Je n'ai pas vraiment réfléchi, même mes plugins sont tous en lowercase..

Merci pour votre réponse, et bonne journée.
